/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// Page order within each section comes from each page's sidebar_position frontmatter.
const sidebars = {
  cockpitSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [{ type: 'autogenerated', dirName: 'core-concepts' }],
    },
    {
      type: 'category',
      label: 'Projects & Tenants',
      items: [{ type: 'autogenerated', dirName: 'projects-and-tenants' }],
    },
    {
      type: 'category',
      label: 'Users & Access',
      items: [{ type: 'autogenerated', dirName: 'users-and-access' }],
    },
    'multitenancy/multitenancy',
    {
      type: 'category',
      label: 'External Services',
      items: [{ type: 'autogenerated', dirName: 'external-services' }],
    },
    {
      type: 'category',
      label: 'Account & Environment',
      items: [{ type: 'autogenerated', dirName: 'account-and-environment' }],
    },
    {
      type: 'category',
      label: 'Administration',
      items: [{ type: 'autogenerated', dirName: 'administration' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
}

module.exports = sidebars
