/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    'intro',
    'overview',
    {
      type: 'category',
      label: 'Tutorial',
      link: {
        type: 'doc',
        id: 'tutorial/index',
      },
      items: [
        {
          type: 'category',
          label: 'Introductory tutorial',
          link: {
            type: 'doc',
            id: 'tutorial/basic/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'tutorial/basic/modules',
            },
          ],
        },
        {
          type: 'category',
          label: 'Real-time communication and analysis tutorial',
          link: {
            type: 'doc',
            id: 'tutorial/pubsub/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'tutorial/pubsub/modules',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Quickstart',
      link: {
        type: 'generated-index',
        title: 'Quickstart',
        slug: '/quickstart/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'quickstart',
        },
      ],
    },
    {
      type: 'category',
      label: 'How to',
      link: {
        type: 'generated-index',
        title: 'How To',
        slug: '/how-to/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'how-to',
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanations',
      link: {
        type: 'generated-index',
        title: 'Explanations',
        slug: '/explanations/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'explanations',
        },
      ],
    },
  ],
};

module.exports = sidebars;
