/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebarsSDK can be generated from the filesystem, or explicitly defined here.

 Create as many sidebarsSDK as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsSDK = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  sdkSidebar: [
    'intro',
    'quick-start',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial/index'],
    },
    {
      type: 'category',
      label: 'How To',
      link: {
        type: 'generated-index',
        title: 'How To',
        slug: '/how-to/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'how-to',
        },
      ],
    },
    {
      type: 'category',
      label: 'References',
      link: {
        type: 'doc',
        id: 'references/modules',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'references',
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanations',
      link: {
        type: 'doc',
        id: 'explanations',
      },
      // Can't use autogenerated items, but we may be able to do javascript code to retrieve them.
      items: [
        {
          type: 'category',
          label: 'End-to-end encryption',
          link: {
            type: 'generated-index',
            title: 'End-to-end encryption',
            slug: '/explanations/encryption',
          },
          items: [
            'explanations/encryption/introduction'
          ],
        }
      ],
    },
    'glossary'
  ],
};

module.exports = sidebarsSDK;
